function [Leg3,Site3,Topcm2,Botcm1,Depthmbsf3,CalciumCamM1,ChlorinityClmM1,MagnesiumMgmM1,pHpHna1,SodiumNamM1,StrontiumSruM1,SulfateSO4mM1,SilicaH4SiO4uM1,AlkalinityALKmM1,SalinitySALna1] = importfile_water(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE Import data from a spreadsheet
%   [Leg3,Site3,Topcm2,Botcm1,Depthmbsf3,CalciumCamM1,ChlorinityClmM1,MagnesiumMgmM1,pHpHna1,SodiumNamM1,StrontiumSruM1,SulfateSO4mM1,SilicaH4SiO4uM1,AlkalinityALKmM1,SalinitySALna1]
%   = IMPORTFILE(FILE) reads data from the first worksheet in the Microsoft
%   Excel spreadsheet file named FILE and returns the data as column
%   vectors.
%
%   [Leg3,Site3,Topcm2,Botcm1,Depthmbsf3,CalciumCamM1,ChlorinityClmM1,MagnesiumMgmM1,pHpHna1,SodiumNamM1,StrontiumSruM1,SulfateSO4mM1,SilicaH4SiO4uM1,AlkalinityALKmM1,SalinitySALna1]
%   = IMPORTFILE(FILE,SHEET) reads from the specified worksheet.
%
%   [Leg3,Site3,Topcm2,Botcm1,Depthmbsf3,CalciumCamM1,ChlorinityClmM1,MagnesiumMgmM1,pHpHna1,SodiumNamM1,StrontiumSruM1,SulfateSO4mM1,SilicaH4SiO4uM1,AlkalinityALKmM1,SalinitySALna1]
%   = IMPORTFILE(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.
%
%	Non-numeric cells are replaced with: NaN
%
% Example:
%   [Leg3,Site3,Topcm2,Botcm1,Depthmbsf3,CalciumCamM1,ChlorinityClmM1,MagnesiumMgmM1,pHpHna1,SodiumNamM1,StrontiumSruM1,SulfateSO4mM1,SilicaH4SiO4uM1,AlkalinityALKmM1,SalinitySALna1] = importfile('water.xlsx','Sheet1',2,13807);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2018/07/05 11:08:08

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 2;
    endRow = 13807;
end

%% Import the data
[~, ~, raw] = xlsread(workbookFile, sheetName, sprintf('A%d:O%d',startRow(1),endRow(1)));
for block=2:length(startRow)
    [~, ~, tmpRawBlock] = xlsread(workbookFile, sheetName, sprintf('A%d:O%d',startRow(block),endRow(block)));
    raw = [raw;tmpRawBlock]; %#ok<AGROW>
end
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
I = cellfun(@(x) ischar(x), raw);
raw(I) = {NaN};
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
Leg3 = data(:,1);
Site3 = data(:,2);
Topcm2 = data(:,3);
Botcm1 = data(:,4);
Depthmbsf3 = data(:,5);
CalciumCamM1 = data(:,6);
ChlorinityClmM1 = data(:,7);
MagnesiumMgmM1 = data(:,8);
pHpHna1 = data(:,9);
SodiumNamM1 = data(:,10);
StrontiumSruM1 = data(:,11);
SulfateSO4mM1 = data(:,12);
SilicaH4SiO4uM1 = data(:,13);
AlkalinityALKmM1 = data(:,14);
SalinitySALna1 = data(:,15);

